services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY} # Replace with your desired username
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY} # Replace with your desired password
    volumes:
      - minio:/data # Mount host directory to container's data directory
    command: server /data --console-address ":9001"

volumes:
  pg:
  minio: