[DEFAULT]
ARGON_TIME_COST = 2
ARGON_MEMORY_COST = 204800
ARGON_PARALLELISM = 4
ARGON_SALT_LENGTH = 16
ARGON_HASH_LENGTH = 32

[DEV]
SERVER_ADDRESS = "127.0.0.1"
SERVER_PORT = 8000

[PROD]
SERVER_ADDRESS = "0.0.0.0"
SERVER_PORT = 9000
